patterns = {
    "ace05e": {
        "Business:Declare-Bankruptcy": {
            "event subtype": "declare bankruptcy",
            "event type": "Business:Declare-Bankruptcy",
            "keywords": ['bankruptcy', 'bankrupt', 'Bankruptcy'],
            "event description": "The event is related to some organization declaring bankruptcy.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Org} declared bankruptcy.",
            "valid roles": ["Org"],
        },
        "Business:End-Org": {
            "event subtype": "end organization",
            "event type": "Business:End-Org",
            "keywords": ['dissolve', 'disbanded', 'close'],
            "event description": "The event is related to some organization ceasing to exist.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Org} dissolved.",
            "valid roles": ["Org", "Place"],
        },
        "Business:Merge-Org": {
            "event subtype": "merge organization",
            "event type": "Business:Merge-Org",
            "keywords": ['merge', 'merging', 'merger'],
            "event description": "The event is related to two or more organization coming together to form a new organization.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Org} was merged.",
            "valid roles": ["Org"],
        },
        "Business:Start-Org": {
            "event subtype": "start organization",
            "event type": "Business:Start-Org",
            "keywords": ['founded', 'create', 'launch'],
            "event description": "The event is related to a new organization being created.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Agent} launched {ROLE_Org} in {ROLE_Place}.",
            "valid roles": ["Agent", "Org", "Place"],
        },
        "Conflict:Attack": {
            "event subtype": "attack",
            "event type": "Conflict:Attack",
            "keywords": ['war', 'attack', 'terrorism'],
            "event description": "The event is related to conflict and some violent physical act.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Attacker} attacked {ROLE_Target} by {ROLE_Instrument} in {ROLE_Place}.",
            "valid roles": ["Attacker", "Target", "Instrument", "Place", "Agent"],
        },
        "Conflict:Demonstrate": {
            "event subtype": "demonstrate",
            "event type": "Conflict:Demonstrate",
            "keywords": ['rally', 'protest', 'demonstrate'],
            "event description": "The event is related to a large number of people coming together to protest.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} protested at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Contact:Meet": {
            "event subtype": "meet",
            "event type": "Contact:Meet",
            "keywords": ['meeting', 'met', 'summit'],
            "event description": "The event is related to a group of people meeting and interacting with one another face-to-face.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} met at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Contact:Phone-Write": {
            "event subtype": "phone write",
            "event type": "Contact:Phone-Write",
            "keywords": ['call', 'communicate', 'e-mail'],
            "event description": "The event is related to people phone calling or messaging one another.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} called or texted messages at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Justice:Acquit": {
            "event subtype": "acquit",
            "event type": "Justice:Acquit",
            "keywords": ['acquitted', 'acquittal', 'acquit'],
            "event description": "The event is related to someone being acquitted.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was acquitted of the charges by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Adjudicator"],
        },
        "Justice:Appeal": {
            "event subtype": "appeal",
            "event type": "Justice:Appeal",
            "keywords": ['appeal', 'appealing', 'appeals'],
            "event description": "The event is related to someone appealing the decision of a court.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Plaintiff} in {ROLE_Place} appealed the adjudication from {ROLE_Adjudicator}.",
            "valid roles": ["Plaintiff", "Place", "Adjudicator"],
        },
        "Justice:Arrest-Jail": {
            "event subtype": "arrest jail",
            "event type": "Justice:Arrest-Jail",
            "keywords": ['arrest', 'jail', 'detained'],
            "event description": "The event is related to a person getting arrested or a person being sent to jail.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was sent to jailed or arrested by {ROLE_Agent} in {ROLE_Place}.",
            "valid roles": ["Person", "Agent", "Place"],
        },
        "Justice:Charge-Indict": {
            "event subtype": "charge indict",
            "event type": "Justice:Charge-Indict",
            "keywords": ['indict', 'charged', 'accused'],
            "event description": "The event is related to someone or some organization being accused of a crime.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was charged by {ROLE_Prosecutor} in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Prosecutor", "Place", "Adjudicator"],
        }, 
        "Justice:Convict": {
            "event subtype": "convict",
            "event type": "Justice:Convict",
            "keywords": ['convicted', 'guilty', 'verdict'],
            "event description": "The event is related to someone being found guilty of a crime.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was convicted of a crime in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Place", "Adjudicator"],
        }, 
        "Justice:Execute": {
            "event subtype": "execute",
            "event type": "Justice:Execute",
            "keywords": ['execution', 'executed', 'execute'],
            "event description": "The event is related to someone being executed to death.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was executed by {ROLE_Agent} at {ROLE_Place}.",
            "valid roles": ["Person", "Agent", "Place"],
        },
        "Justice:Extradite": {
            "event subtype": "extradite",
            "event type": "Justice:Extradite",
            "keywords": ['extradition', 'extradited', 'extraditing'],
            "event description": "The event is related to justice. The event occurs when a person was extradited from one place to another place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was extradicted to {ROLE_Destination} from {ROLE_Origin}, and {ROLE_Agent} was responsible for the extradition.",
            "valid roles": ["Person", "Destination", "Origin", "Agent"],
        },
        "Justice:Fine": {
            "event subtype": "fine",
            "event type": "Justice:Fine",
            "keywords": ['fine', 'fined', 'payouts'],
            "event description": "The event is related to someone being issued a financial punishment.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} in {ROLE_Place} was ordered by {ROLE_Adjudicator} to pay a fine.",
            "valid roles": ["Entity", "Place", "Adjudicator"], 
        },
        "Justice:Pardon": {
            "event subtype": "pardon",
            "event type": "Justice:Pardon",
            "keywords": ['pardon', 'pardoned', 'remission'],
            "event description": "The event is related to someone being pardoned.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} received a pardon from {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Adjudicator"],
        }, 
        "Justice:Release-Parole": {
            "event subtype": "release parole",
            "event type": "Justice:Release-Parole",
            "keywords": ['parole', 'release', 'free'],
            "event description": "The event is related to an end to someone's custody in prison.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was released by {ROLE_Entity} from {ROLE_Place}.",
            "valid roles": ["Person", "Entity", "Place"],
        },
        "Justice:Sentence": {
            "event subtype": "sentence",
            "event type": "Justice:Sentence",
            "keywords": ['sentenced', 'sentencing', 'sentence'],
            "event description": "The event is related to someone being sentenced to punishment because of a crime.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was sentenced to punishment in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Place", "Adjudicator"],
        }, 
        "Justice:Sue": {
            "event subtype": "sue",
            "event type": "Justice:Sue",
            "keywords": ['sue', 'lawsuit', 'suit'],
            "event description": "The event is related to a court proceeding that has been initiated and someone sue the other.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was sued by {ROLE_Plaintiff} in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        }, 
        "Justice:Trial-Hearing": {
            "event subtype": "trial hearing",
            "event type": "Justice:Trial-Hearing",
            "keywords": ['trial', 'hearing', 'proceeding'],
            "event description": "The event is related to a trial or hearing for someone.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant}, prosecuted by {ROLE_Prosecutor}, faced a trial in {ROLE_Place}, and the hearing was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        }, 
        "Life:Be-Born": {
            "event subtype": "born",
            "event type": "Life:Be-Born",
            "keywords": ['born', 'birth', 'bore'],
            "event description": "The event is related to life and someone is given birth to.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was born in {ROLE_Place}.",
            "valid roles": ["Person", "Place"], 
        }, 
        "Life:Die": {
            "event subtype": "die",
            "event type": "Life:Die",
            "keywords": ['kill', 'death', 'assassination'],
            "event description": "The event is related to life and someone died.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Agent} led to {ROLE_Victim} died by {ROLE_Instrument} in {ROLE_Place}.",
            "valid roles": ["Agent", "Victim", "Instrument", "Place"],
        },
        "Life:Divorce": {
            "event subtype": "divorce",
            "event type": "Life:Divorce",
            "keywords": ['divorce', 'divorced', 'Divorce'],
            "event description": "The event is related to life and someone was divorced.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} divorced in {ROLE_Place}.",
            "valid roles": ["Person", "Place"], 
        }, 
        "Life:Injure": {
            "event subtype": "injure",
            "event type": "Life:Injure",
            "keywords": ['injure', 'wounded', 'hurt'],
            "event description": "The event is related to life and someone is injured.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Agent} led to {ROLE_Victim} injured by {ROLE_Instrument} in {ROLE_Place}.",
            "valid roles": ["Agent", "Victim", "Instrument", "Place"],
        },
        "Life:Marry": {
            "event subtype": "marry",
            "event type": "Life:Marry",
            "keywords": ['marry', 'marriage', 'married'],
            "event description": "The event is related to life and someone is married.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} got married in {ROLE_Place}.",
            "valid roles": ["Person", "Place"], 
        },
        "Movement:Transport": {
            "event subtype": "transport",
            "event type": "Movement:Transport",
            "keywords": ['travel', 'go', 'move'],
            "event description": "The event is related to movement. The event occurs when a weapon or vehicle is moved from one place to another.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Artifact} was sent to {ROLE_Destination} from {ROLE_Origin} by {ROLE_Vehicle}, and {ROLE_Agent} was responsible for the transport.",
            "valid roles": ["Artifact", "Destination", "Origin", "Vehicle", "Agent", "Place"], 
        },
        "Personnel:Elect": {
            "event subtype": "elect",
            "event type": "Personnel:Elect",
            "keywords": ['election', 'elect', 'elected'],
            "event description": "The event is related to a candidate wins an election.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was elected a position, and the election was voted by {ROLE_Entity} in {ROLE_Place}.",
            "valid roles": ["Person", "Entity", "Place"], 
        },
        "Personnel:End-Position": {
            "event subtype": "end position",
            "event type": "Personnel:End-Position",
            "keywords": ['former', 'laid off', 'fired'],
            "event description": "The event is related to a person stops working for an organization or a hiring manager.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} stopped working for {ROLE_Entity} at {ROLE_Place}.",
            "valid roles": ["Person", "Entity", "Place"],
        }, 
        "Personnel:Nominate": {
            "event subtype": "nominate",
            "event type": "Personnel:Nominate",
            "keywords": ['named', 'nomination', 'nominate'],
            "event description": "The event is related to a person being nominated for a position.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was nominated by {ROLE_Entity} to do a job.",
            "valid roles": ["Person", "Agent"], 
        },  
        "Personnel:Start-Position": {
            "event subtype": "start position",
            "event type": "Personnel:Start-Position",
            "keywords": ['hire', 'appoint', 'join'],
            "event description": "The event is related to a person begins working for an organization or a hiring manager.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} got new job and was hired by {ROLE_Entity} in {ROLE_Place}.",
            "valid roles": ["Person", "Entity", "Place"], 
        },  
        "Transaction:Transfer-Money": {
            "event subtype": "transfer money",
            "event type": "Transaction:Transfer-Money",
            "keywords": ['pay', 'donation', 'loan'],
            "event description": "The event is related to transaction. The event occurs when someone is giving, receiving, borrowing, or lending money.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Giver} paid {ROLE_Recipient} in {ROLE_Place}.",
            "valid roles": ["Giver", "Recipient", "Place", "Beneficiary"], 
        },  
        "Transaction:Transfer-Ownership": {
            "event subtype": "transfer ownership",
            "event type": "Transaction:Transfer-Ownership",
            "keywords": ['sell', 'buy', 'acquire'],
            "event description": "The event is related to transaction. The event occurs when an item or an organization is sold or gave to some other.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Buyer} got {ROLE_Artifact} from {ROLE_Place} in {ROLE_Place}.",
            "valid roles": ["Buyer", "Artifact", "Seller", "Place", "Beneficiary"], 
        }, 
    }, 
    "ere": {
        "Business:Declare-Bankruptcy": {
            "event subtype": "declare bankruptcy",
            "event type": "Business:Declare-Bankruptcy",
            "keywords": ['bankruptcy', 'bankrupt', 'Bankruptcy'],
            "event description": "The event is related to some organization declaring bankruptcy.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Org} declared bankruptcy.",
            "valid roles": ["Org"],
        },
        "Business:End-Org": {
            "event subtype": "end organization",
            "event type": "Business:End-Org",
            "keywords": ['dissolve', 'disbanded', 'close'],
            "event description": "The event is related to some organization ceasing to exist.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Org} dissolved.",
            "valid roles": ["Org"],
        },
        "Business:Merge-Org": {
            "event subtype": "merge organization",
            "event type": "Business:Merge-Org",
            "keywords": ['merge', 'merging', 'merger'],
            "event description": "The event is related to two or more organization coming together to form a new organization.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Org} was merged.",
            "valid roles": ["Org"],
        },
        "Business:Start-Org": {
            "event subtype": "start organization",
            "event type": "Business:Start-Org",
            "keywords": ['founded', 'create', 'launch'],
            "event description": "The event is related to a new organization being created.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Agent} launched {ROLE_Org} in {ROLE_Place}.",
            "valid roles": ["Agent", "Org", "Place"],
        },
        "Conflict:Attack": {
            "event subtype": "attack",
            "event type": "Conflict:Attack",
            "keywords": ['war', 'attack', 'terrorism'],
            "event description": "The event is related to conflict and some violent physical act.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Attacker} attacked {ROLE_Target} by {ROLE_Instrument} in {ROLE_Place}.",
            "valid roles": ["Attacker", "Target", "Instrument", "Place", "Agent"],
        },
        "Conflict:Demonstrate": {
            "event subtype": "demonstrate",
            "event type": "Conflict:Demonstrate",
            "keywords": ['rally', 'protest', 'demonstrate'],
            "event description": "The event is related to a large number of people coming together to protest.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} protested at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Contact:Meet": {
            "event subtype": "meet",
            "event type": "Contact:Meet",
            "keywords": ['meeting', 'met', 'summit'],
            "event description": "The event is related to a group of people meeting and interacting with one another face-to-face.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} met at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Contact:Correspondence": {
            "event subtype": "contact correspondence",
            "event type": "Contact:Correspondence",
            "keywords": ['call', 'teleconference', 'e-mail'],
            "event description": "The event happens when a face‐to‐face meeting between sender and receiver is not explicitly stated. This includes written, phone, or electronic communication.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} contacted each other at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Contact:Broadcast": {
            "event subtype": "broadcast",
            "event type": "Contact:Broadcast",
            "keywords": ['statement', 'announce', 'say'],
            "event description": "The event happens when a person or an organization contact with the media and other publicity or announcement conference.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} made announcement to {ROLE_Audience} at {ROLE_Place}.",
            "valid roles": ["Entity", "Audience", "Place"],
        },
        "Contact:Contact": {
            "event subtype": "contact",
            "event type": "Contact:Contact",
            "keywords": ['said', 'talk', 'tell'],
            "event description": "The event happens when there is no explicit mention of contact ways of communication.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} talked to each other at {ROLE_Place}.",
            "valid roles": ["Entity", "Place"],
        },
        "Justice:Acquit": {
            "event subtype": "acquit",
            "event type": "Justice:Acquit",
            "keywords": ['acquitted', 'acquittal', 'acquit'],
            "event description": "The event is related to someone being acquitted.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was acquitted of the charges by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Adjudicator"],
        },
        "Justice:Appeal": {
            "event subtype": "appeal",
            "event type": "Justice:Appeal",
            "keywords": ['appeal', 'appealing', 'appeals'],
            "event description": "The event is related to someone appealing the decision of a court.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} in {ROLE_Place} appealed the adjudication from {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Place", "Adjudicator"],
        },
        "Justice:Arrest-Jail": {
            "event subtype": "arrest jail",
            "event type": "Justice:Arrest-Jail",
            "keywords": ['arrest', 'jail', 'detained'],
            "event description": "The event is related to a person getting arrested or a person being sent to jail.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was sent to jailed or arrested by {ROLE_Agent} in {ROLE_Place}.",
            "valid roles": ["Person", "Agent", "Place"],
        },
        "Justice:Charge-Indict": {
            "event subtype": "charge indict",
            "event type": "Justice:Charge-Indict",
            "keywords": ['indict', 'charged', 'accused'],
            "event description": "The event is related to someone or some organization being accused of a crime.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was charged by {ROLE_Prosecutor} in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Prosecutor", "Place", "Adjudicator"],
        }, 
        "Justice:Convict": {
            "event subtype": "convict",
            "event type": "Justice:Convict",
            "keywords": ['convicted', 'guilty', 'verdict'],
            "event description": "The event is related to someone being found guilty of a crime.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was convicted of a crime in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Place", "Adjudicator"],
        }, 
        "Justice:Execute": {
            "event subtype": "execute",
            "event type": "Justice:Execute",
            "keywords": ['execution', 'executed', 'execute'],
            "event description": "The event is related to someone being executed to death.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was executed by {ROLE_Agent} at {ROLE_Place}.",
            "valid roles": ["Person", "Agent", "Place"],
        },
        "Justice:Extradite": {
            "event subtype": "extradite",
            "event type": "Justice:Extradite",
            "keywords": ['extradition', 'extradited', 'extraditing'],
            "event description": "The event is related to justice. The event occurs when a person was extradited from one place to another place.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was extradicted to {ROLE_Destination} from {ROLE_Origin}, and {ROLE_Agent} was responsible for the extradition.",
            "valid roles": ["Person", "Destination", "Origin", "Agent"],
        },
        "Justice:Fine": {
            "event subtype": "fine",
            "event type": "Justice:Fine",
            "keywords": ['fine', 'fined', 'payouts'],
            "event description": "The event is related to someone being issued a financial punishment.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Entity} in {ROLE_Place} was ordered by {ROLE_Adjudicator} to pay a fine.",
            "valid roles": ["Entity", "Place", "Adjudicator"], 
        },
        "Justice:Pardon": {
            "event subtype": "pardon",
            "event type": "Justice:Pardon",
            "keywords": ['pardon', 'pardoned', 'remission'],
            "event description": "The event is related to someone being pardoned.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} received a pardon from {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Adjudicator"],
        }, 
        "Justice:Release-Parole": {
            "event subtype": "release parole",
            "event type": "Justice:Release-Parole",
            "keywords": ['parole', 'release', 'free'],
            "event description": "The event is related to an end to someone's custody in prison.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was released by {ROLE_Agent} from {ROLE_Place}.",
            "valid roles": ["Person", "Agent", "Place"],
        },
        "Justice:Sentence": {
            "event subtype": "sentence",
            "event type": "Justice:Sentence",
            "keywords": ['sentenced', 'sentencing', 'sentence'],
            "event description": "The event is related to someone being sentenced to punishment because of a crime.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was sentenced to punishment in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Place", "Adjudicator"],
        }, 
        "Justice:Sue": {
            "event subtype": "sue",
            "event type": "Justice:Sue",
            "keywords": ['sue', 'lawsuit', 'suit'],
            "event description": "The event is related to a court proceeding that has been initiated and someone sue the other.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant} was sued by {ROLE_Plaintiff} in {ROLE_Place}, and the adjudication was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        }, 
        "Justice:Trial-Hearing": {
            "event subtype": "trial hearing",
            "event type": "Justice:Trial-Hearing",
            "keywords": ['trial', 'hearing', 'proceeding'],
            "event description": "The event is related to a trial or hearing for someone.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Defendant}, prosecuted by {ROLE_Prosecutor}, faced a trial in {ROLE_Place}. The hearing was judged by {ROLE_Adjudicator}.",
            "valid roles": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        }, 
        "Life:Be-Born": {
            "event subtype": "born",
            "event type": "Life:Be-Born",
            "keywords": ['born', 'birth', 'bore'],
            "event description": "The event is related to life and someone is given birth to.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was born in {ROLE_Place}.",
            "valid roles": ["Person", "Place"], 
        }, 
        "Life:Die": {
            "event subtype": "die",
            "event type": "Life:Die",
            "keywords": ['kill', 'death', 'assassination'],
            "event description": "The event is related to life and someone died.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Agent} led to {ROLE_Victim} died by {ROLE_Instrument} in {ROLE_Place}.",
            "valid roles": ["Agent", "Victim", "Instrument", "Place"],
        },
        "Life:Divorce": {
            "event subtype": "divorce",
            "event type": "Life:Divorce",
            "keywords": ['divorce', 'divorced', 'Divorce'],
            "event description": "The event is related to life and someone was divorced.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} divorced in {ROLE_Place}.",
            "valid roles": ["Person", "Place"], 
        }, 
        "Life:Injure": {
            "event subtype": "injure",
            "event type": "Life:Injure",
            "keywords": ['injure', 'wounded', 'hurt'],
            "event description": "The event is related to life and someone is injured.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Agent} led to {ROLE_Victim} injured by {ROLE_Instrument} in {ROLE_Place}.",
            "valid roles": ["Agent", "Victim", "Instrument", "Place"],
        },
        "Life:Marry": {
            "event subtype": "marry",
            "event type": "Life:Marry",
            "keywords": ['marry', 'marriage', 'married'],
            "event description": "The event is related to life and someone is married.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} got married in {ROLE_Place}.",
            "valid roles": ["Person", "Place"], 
        },
        "Movement:Transport-Person": {
            "event subtype": "transport person",
            "event type": "Movement:Transport-Person",
            "keywords": ['travel', 'go', 'move'],
            "event description": "The event is related to movement. The event occurs when a person moves or is moved from one place to another.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was moved to {ROLE_Destination} from {ROLE_Origin} by {ROLE_Instrument}, and {ROLE_Agent} was responsible for the movement.",
            "valid roles": ["Person", "Destination", "Origin", "Instrument", "Agent"], 
        },
        "Movement:Transport-Artifact": {
            "event subtype": "transport artifact",
            "event type": "Movement:Transport-Artifact",
            "keywords": ['export', 'deliver', 'send'],
            "event description": "The event is related to movement. The event occurs when an artifact, like items or weapon, is moved from one place to another.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Artifact} was sent to {ROLE_Destination} from {ROLE_Origin}, and {ROLE_Agent} was responsible for the transport.",
            "valid roles": ["Artifact", "Destination", "Origin", "Agent"], 
        },
        "Personnel:Elect": {
            "event subtype": "elect",
            "event type": "Personnel:Elect",
            "keywords": ['election', 'elect', 'elected'],
            "event description": "The event is related to a candidate wins an election.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was elected a position, and the election was voted by {ROLE_Agent} in {ROLE_Place}.",
            "valid roles": ["Person", "Agent", "Place"], 
        },
        "Personnel:End-Position": {
            "event subtype": "end position",
            "event type": "Personnel:End-Position",
            "keywords": ['former', 'laid off', 'fired'],
            "event description": "The event is related to a person stops working for an organization or a hiring manager.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} stopped working for {ROLE_Entity} at {ROLE_Place}.",
            "valid roles": ["Person", "Entity", "Place"],
        }, 
        "Personnel:Nominate": {
            "event subtype": "nominate",
            "event type": "Personnel:Nominate",
            "keywords": ['named', 'nomination', 'nominate'],
            "event description": "The event is related to a person being nominated for a position.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} was nominated by {ROLE_Entity} to do a job.",
            "valid roles": ["Person", "Agent"], 
        },  
        "Personnel:Start-Position": {
            "event subtype": "start position",
            "event type": "Personnel:Start-Position",
            "keywords": ['hire', 'appoint', 'join'],
            "event description": "The event is related to a person begins working for an organization or a hiring manager.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Person} got new job and was hired by {ROLE_Entity} in {ROLE_Place}.",
            "valid roles": ["Person", "Entity", "Place"], 
        },  
        "Transaction:Transfer-Money": {
            "event subtype": "transfer money",
            "event type": "Transaction:Transfer-Money",
            "keywords": ['pay', 'donation', 'loan'],
            "event description": "The event is related to transaction. The event occurs when someone is giving, receiving, borrowing, or lending money.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Giver} paid {ROLE_Recipient} in {ROLE_Place}.",
            "valid roles": ["Giver", "Recipient", "Place", "Beneficiary"], 
        },  
        "Transaction:Transfer-Ownership": {
            "event subtype": "transfer ownership",
            "event type": "Transaction:Transfer-Ownership",
            "keywords": ['sell', 'buy', 'acquire'],
            "event description": "The event is events refer to the buying, selling, loaning, borrowing, giving, receiving, bartering, stealing, or renting of physical items, assets,or organizations.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "The ownership of {ROLE_Thing} from {ROLE_Giver} was transferred to {ROLE_Recipient} at {ROLE_Place}.",
            "valid roles": ["Thing", "Giver", "Recipient", "Place", "Beneficiary"], 
        }, 
        "Transaction:Transaction": {
            "event subtype": "transaction",
            "event type": "Transaction:Transaction",
            "keywords": ['receive', 'give', 'get'],
            "event description": "The event is related to transaction. The event occurs when someone is giving, receiving, borrowing, or lending something when you cannot tell whether it is money or an asset in the context.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Giver} give some things to {ROLE_Recipient} in {ROLE_Place}.",
            "valid roles": ["Giver", "Recipient", "Place", "Beneficiary"], 
        },
        "Manufacture:Artifact": {
            "event subtype": "artifact",
            "event type": "Manufacture:Artifact",
            "keywords": ['develop', 'produce', 'construct'],
            "event description": "The event occurs whenever a person or an organization builds or manufactures a facility or a weapon, etc.",
            "ED template": "Event trigger is {Trigger}.",
            "EAE template": "{ROLE_Artifact} was built by {ROLE_Agent} in {ROLE_Place}.",
            "valid roles": ["Artifact", "Agent", "Place"], 
        }, 
    },
}